# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 202a9ec9c52dfc910952695d79827000778b0483fbac6c341a68c76084e52446659d15c65e9ff6de89ad868f11b69119976875bcd8efc4d06cbf1256e3268908

test:
  secret_key_base: c4af41aa73e79b58d6bf893ea10c80572f5ac5e39b0a0832131910ee34116f228ac462dcd5cd80a354ae6d8c5ee8b741ec514845b86875cb2f35d259aa781f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
